//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotsReplayReader.Resources.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class i18n {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal i18n() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HotsReplayReader.Resources.Language.i18n", typeof(i18n).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EN-US.
        /// </summary>
        internal static string DeepLLang {
            get {
                return ResourceManager.GetString("DeepLLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alterac Pass.
        /// </summary>
        internal static string MapAlteracPass {
            get {
                return ResourceManager.GetString("MapAlteracPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battlefield of Eternity.
        /// </summary>
        internal static string MapBattlefieldOfEternity {
            get {
                return ResourceManager.GetString("MapBattlefieldOfEternity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blackheart&apos;s Bay.
        /// </summary>
        internal static string MapBlackheartsBay {
            get {
                return ResourceManager.GetString("MapBlackheartsBay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Braxis Holdout.
        /// </summary>
        internal static string MapBraxisHoldout {
            get {
                return ResourceManager.GetString("MapBraxisHoldout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sky Temple.
        /// </summary>
        internal static string MapControlPoints {
            get {
                return ResourceManager.GetString("MapControlPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tomb of the Spider Queen.
        /// </summary>
        internal static string MapCrypts {
            get {
                return ResourceManager.GetString("MapCrypts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cursed Hollow.
        /// </summary>
        internal static string MapCursedHollow {
            get {
                return ResourceManager.GetString("MapCursedHollow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dragon Shire.
        /// </summary>
        internal static string MapDragonShire {
            get {
                return ResourceManager.GetString("MapDragonShire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hanamura Temple.
        /// </summary>
        internal static string MapHanamura {
            get {
                return ResourceManager.GetString("MapHanamura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haunted Mines.
        /// </summary>
        internal static string MapHauntedMines {
            get {
                return ResourceManager.GetString("MapHauntedMines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Garden of Terror.
        /// </summary>
        internal static string MapHauntedWoods {
            get {
                return ResourceManager.GetString("MapHauntedWoods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infernal Shrines.
        /// </summary>
        internal static string MapShrines {
            get {
                return ResourceManager.GetString("MapShrines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Towers of Doom.
        /// </summary>
        internal static string MapTowersOfDoom {
            get {
                return ResourceManager.GetString("MapTowersOfDoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volskaya Foundry.
        /// </summary>
        internal static string MapVolskaya {
            get {
                return ResourceManager.GetString("MapVolskaya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warhead Junction.
        /// </summary>
        internal static string MapWarhead_Junction {
            get {
                return ResourceManager.GetString("MapWarhead Junction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AI.
        /// </summary>
        internal static string strAI {
            get {
                return ResourceManager.GetString("strAI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adept.
        /// </summary>
        internal static string strAIAdept {
            get {
                return ResourceManager.GetString("strAIAdept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beginner.
        /// </summary>
        internal static string strAIBeginner {
            get {
                return ResourceManager.GetString("strAIBeginner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Difficulty.
        /// </summary>
        internal static string strAIDifficulty {
            get {
                return ResourceManager.GetString("strAIDifficulty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elite.
        /// </summary>
        internal static string strAIElite {
            get {
                return ResourceManager.GetString("strAIElite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recruit.
        /// </summary>
        internal static string strAIRecruit {
            get {
                return ResourceManager.GetString("strAIRecruit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veteran.
        /// </summary>
        internal static string strAIVeteran {
            get {
                return ResourceManager.GetString("strAIVeteran", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue Team.
        /// </summary>
        internal static string strBlueTeam {
            get {
                return ResourceManager.GetString("strBlueTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        internal static string strDuration {
            get {
                return ResourceManager.GetString("strDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player.
        /// </summary>
        internal static string strPlayer {
            get {
                return ResourceManager.GetString("strPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red Team.
        /// </summary>
        internal static string strRedTeam {
            get {
                return ResourceManager.GetString("strRedTeam", resourceCulture);
            }
        }
    }
}
