<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
	<TargetFramework>net9.0-windows</TargetFramework>
	<Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationIcon>images\HotsReplayReader.ico</ApplicationIcon>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <Version>0.2.0</Version>
    <AssemblyVersion>$(Version)</AssemblyVersion>
    <FileVersion>$(Version)</FileVersion>
    <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
	<SupportedOSPlatform>windows</SupportedOSPlatform>
    <NoWarn>$(NoWarn);MSB3277</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Classes\**" />
    <EmbeddedResource Remove="Classes\**" />
    <None Remove="Classes\**" />

    <Compile Remove="HotsReplayReader.Updater\**" />
    <EmbeddedResource Remove="HotsReplayReader.Updater\**" />
    <None Remove="HotsReplayReader.Updater\**" />
    <Content Remove="HotsReplayReader.Updater\**" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="images\HotsReplayReader.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.4129.50" />
    <PackageReference Include="WebView2.Runtime.X64" Version="132.0.2957.140" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Resources\Abilitytalents.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>AbilityTalents.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\Flags.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Flags.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\HeroesIcon.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>HeroesIcon.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\HotsEmoticons.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>HotsEmoticons.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\HotsResources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>HotsResources.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\Language\i18n.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>i18n.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\MatchAwardsImg.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>MatchAwardsImg.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\MinimapIcons.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>MinimapIcons.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Resources\AbilityTalents.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Abilitytalents.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Flags.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Flags.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\HeroesIcon.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>HeroesIcon.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\HotsEmoticons.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>HotsEmoticons.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\HotsResources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>HotsResources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Language\i18n.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>i18n.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\MatchAwardsImg.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>MatchAwardsImg.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\MinimapIcons.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>MinimapIcons.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Heroes.Element\Heroes.Element\Heroes.Element.csproj" />
    <ProjectReference Include="..\Heroes.Icons\Heroes.Icons\Heroes.Icons.csproj" />
    <ProjectReference Include="..\Heroes.StormReplayParser\Heroes.StormReplayParser\Heroes.StormReplayParser.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="obj\Debug\$(TargetFramework)\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="HotsReplayReader.Updater\HotsReplayReader.Updater.csproj">
      <ReferenceOutputAssembly>false</ReferenceOutputAssembly>
    </ProjectReference>
  </ItemGroup>
  <Target Name="EmbedUpdaterBeforeBuild" BeforeTargets="PrepareForBuild;PrepareResources">
    <MSBuild Projects="HotsReplayReader.Updater\HotsReplayReader.Updater.csproj" Targets="Build" Properties="Configuration=$(Configuration);TargetFramework=$(TargetFramework)" />
    <ItemGroup>
      <EmbeddedResource Include="HotsReplayReader.Updater\bin\$(Configuration)\$(TargetFramework)\HotsReplayReader.Updater.exe">
        <LogicalName>HotsReplayReader.Updater.exe</LogicalName>
      </EmbeddedResource>
      <EmbeddedResource Include="HotsReplayReader.Updater\bin\$(Configuration)\$(TargetFramework)\HotsReplayReader.Updater.dll">
        <LogicalName>HotsReplayReader.Updater.dll</LogicalName>
      </EmbeddedResource>
      <EmbeddedResource Include="HotsReplayReader.Updater\bin\$(Configuration)\$(TargetFramework)\HotsReplayReader.Updater.runtimeconfig.json">
        <LogicalName>HotsReplayReader.Updater.runtimeconfig.json</LogicalName>
      </EmbeddedResource>
      <EmbeddedResource Include="HotsReplayReader.Updater\bin\$(Configuration)\$(TargetFramework)\HotsReplayReader.Updater.deps.json">
        <LogicalName>HotsReplayReader.Updater.deps.json</LogicalName>
      </EmbeddedResource>
    </ItemGroup>
  </Target>
</Project>