//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotsReplayReader {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MatchAwardsImg {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MatchAwardsImg() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HotsReplayReader.Resources.MatchAwardsImg", typeof(MatchAwardsImg).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_mvp_avenger_blue {
            get {
                object obj = ResourceManager.GetObject("storm_ui_mvp_avenger_blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_mvp_avenger_gold {
            get {
                object obj = ResourceManager.GetObject("storm_ui_mvp_avenger_gold", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_mvp_avenger_red {
            get {
                object obj = ResourceManager.GetObject("storm_ui_mvp_avenger_red", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_mvp_bulwark_blue {
            get {
                object obj = ResourceManager.GetObject("storm_ui_mvp_bulwark_blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_mvp_bulwark_gold {
            get {
                object obj = ResourceManager.GetObject("storm_ui_mvp_bulwark_gold", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_mvp_bulwark_red {
            get {
                object obj = ResourceManager.GetObject("storm_ui_mvp_bulwark_red", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_mvp_cannoneer_blue {
            get {
                object obj = ResourceManager.GetObject("storm_ui_mvp_cannoneer_blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_mvp_cannoneer_gold {
            get {
                object obj = ResourceManager.GetObject("storm_ui_mvp_cannoneer_gold", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_mvp_cannoneer_red {
            get {
                object obj = ResourceManager.GetObject("storm_ui_mvp_cannoneer_red", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_mvp_clutchhealer_blue {
            get {
                object obj = ResourceManager.GetObject("storm_ui_mvp_clutchhealer_blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_mvp_clutchhealer_gold {
            get {
                object obj = ResourceManager.GetObject("storm_ui_mvp_clutchhealer_gold", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_mvp_clutchhealer_red {
            get {
                object obj = ResourceManager.GetObject("storm_ui_mvp_clutchhealer_red", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_mvp_combatmedic_blue {
            get {
                object obj = ResourceManager.GetObject("storm_ui_mvp_combatmedic_blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_mvp_combatmedic_gold {
            get {
                object obj = ResourceManager.GetObject("storm_ui_mvp_combatmedic_gold", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_mvp_combatmedic_red {
            get {
                object obj = ResourceManager.GetObject("storm_ui_mvp_combatmedic_red", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_mvp_dabomb_blue {
            get {
                object obj = ResourceManager.GetObject("storm_ui_mvp_dabomb_blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_mvp_dabomb_gold {
            get {
                object obj = ResourceManager.GetObject("storm_ui_mvp_dabomb_gold", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_mvp_dabomb_red {
            get {
                object obj = ResourceManager.GetObject("storm_ui_mvp_dabomb_red", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_mvp_daredevil_blue {
            get {
                object obj = ResourceManager.GetObject("storm_ui_mvp_daredevil_blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_mvp_daredevil_gold {
            get {
                object obj = ResourceManager.GetObject("storm_ui_mvp_daredevil_gold", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_mvp_daredevil_red {
            get {
                object obj = ResourceManager.GetObject("storm_ui_mvp_daredevil_red", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_mvp_dominator_blue {
            get {
                object obj = ResourceManager.GetObject("storm_ui_mvp_dominator_blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_mvp_dominator_gold {
            get {
                object obj = ResourceManager.GetObject("storm_ui_mvp_dominator_gold", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_mvp_dominator_red {
            get {
                object obj = ResourceManager.GetObject("storm_ui_mvp_dominator_red", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_mvp_escapeartist_blue {
            get {
                object obj = ResourceManager.GetObject("storm_ui_mvp_escapeartist_blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_mvp_escapeartist_gold {
            get {
                object obj = ResourceManager.GetObject("storm_ui_mvp_escapeartist_gold", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_mvp_escapeartist_red {
            get {
                object obj = ResourceManager.GetObject("storm_ui_mvp_escapeartist_red", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_mvp_experienced_blue {
            get {
                object obj = ResourceManager.GetObject("storm_ui_mvp_experienced_blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_mvp_experienced_gold {
            get {
                object obj = ResourceManager.GetObject("storm_ui_mvp_experienced_gold", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_mvp_experienced_red {
            get {
                object obj = ResourceManager.GetObject("storm_ui_mvp_experienced_red", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_mvp_finisher_blue {
            get {
                object obj = ResourceManager.GetObject("storm_ui_mvp_finisher_blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_mvp_finisher_gold {
            get {
                object obj = ResourceManager.GetObject("storm_ui_mvp_finisher_gold", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_mvp_finisher_red {
            get {
                object obj = ResourceManager.GetObject("storm_ui_mvp_finisher_red", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_mvp_gardenterror_blue {
            get {
                object obj = ResourceManager.GetObject("storm_ui_mvp_gardenterror_blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_mvp_gardenterror_gold {
            get {
                object obj = ResourceManager.GetObject("storm_ui_mvp_gardenterror_gold", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_mvp_gardenterror_red {
            get {
                object obj = ResourceManager.GetObject("storm_ui_mvp_gardenterror_red", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_mvp_guardian_blue {
            get {
                object obj = ResourceManager.GetObject("storm_ui_mvp_guardian_blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_mvp_guardian_gold {
            get {
                object obj = ResourceManager.GetObject("storm_ui_mvp_guardian_gold", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_mvp_guardian_red {
            get {
                object obj = ResourceManager.GetObject("storm_ui_mvp_guardian_red", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_mvp_guardianslayer_blue {
            get {
                object obj = ResourceManager.GetObject("storm_ui_mvp_guardianslayer_blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_mvp_guardianslayer_gold {
            get {
                object obj = ResourceManager.GetObject("storm_ui_mvp_guardianslayer_gold", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_mvp_guardianslayer_red {
            get {
                object obj = ResourceManager.GetObject("storm_ui_mvp_guardianslayer_red", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_mvp_hattrick_blue {
            get {
                object obj = ResourceManager.GetObject("storm_ui_mvp_hattrick_blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_mvp_hattrick_gold {
            get {
                object obj = ResourceManager.GetObject("storm_ui_mvp_hattrick_gold", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_mvp_hattrick_red {
            get {
                object obj = ResourceManager.GetObject("storm_ui_mvp_hattrick_red", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_mvp_headhunter_blue {
            get {
                object obj = ResourceManager.GetObject("storm_ui_mvp_headhunter_blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_mvp_headhunter_gold {
            get {
                object obj = ResourceManager.GetObject("storm_ui_mvp_headhunter_gold", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_mvp_headhunter_red {
            get {
                object obj = ResourceManager.GetObject("storm_ui_mvp_headhunter_red", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_mvp_immortalslayer_blue {
            get {
                object obj = ResourceManager.GetObject("storm_ui_mvp_immortalslayer_blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_mvp_immortalslayer_gold {
            get {
                object obj = ResourceManager.GetObject("storm_ui_mvp_immortalslayer_gold", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_mvp_immortalslayer_red {
            get {
                object obj = ResourceManager.GetObject("storm_ui_mvp_immortalslayer_red", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_mvp_jeweler_blue {
            get {
                object obj = ResourceManager.GetObject("storm_ui_mvp_jeweler_blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_mvp_jeweler_gold {
            get {
                object obj = ResourceManager.GetObject("storm_ui_mvp_jeweler_gold", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_mvp_jeweler_red {
            get {
                object obj = ResourceManager.GetObject("storm_ui_mvp_jeweler_red", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_mvp_loyaldefender_blue {
            get {
                object obj = ResourceManager.GetObject("storm_ui_mvp_loyaldefender_blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_mvp_loyaldefender_gold {
            get {
                object obj = ResourceManager.GetObject("storm_ui_mvp_loyaldefender_gold", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_mvp_loyaldefender_red {
            get {
                object obj = ResourceManager.GetObject("storm_ui_mvp_loyaldefender_red", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_mvp_mainhealer_blue {
            get {
                object obj = ResourceManager.GetObject("storm_ui_mvp_mainhealer_blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_mvp_mainhealer_gold {
            get {
                object obj = ResourceManager.GetObject("storm_ui_mvp_mainhealer_gold", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_mvp_mainhealer_red {
            get {
                object obj = ResourceManager.GetObject("storm_ui_mvp_mainhealer_red", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_mvp_masterofthecurse_blue {
            get {
                object obj = ResourceManager.GetObject("storm_ui_mvp_masterofthecurse_blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_mvp_masterofthecurse_gold {
            get {
                object obj = ResourceManager.GetObject("storm_ui_mvp_masterofthecurse_gold", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_mvp_masterofthecurse_red {
            get {
                object obj = ResourceManager.GetObject("storm_ui_mvp_masterofthecurse_red", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_mvp_moneybags_blue {
            get {
                object obj = ResourceManager.GetObject("storm_ui_mvp_moneybags_blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_mvp_moneybags_gold {
            get {
                object obj = ResourceManager.GetObject("storm_ui_mvp_moneybags_gold", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_mvp_moneybags_red {
            get {
                object obj = ResourceManager.GetObject("storm_ui_mvp_moneybags_red", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_mvp_mvp_blue {
            get {
                object obj = ResourceManager.GetObject("storm_ui_mvp_mvp_blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_mvp_mvp_gold {
            get {
                object obj = ResourceManager.GetObject("storm_ui_mvp_mvp_gold", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_mvp_mvp_red {
            get {
                object obj = ResourceManager.GetObject("storm_ui_mvp_mvp_red", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_mvp_painbringer_blue {
            get {
                object obj = ResourceManager.GetObject("storm_ui_mvp_painbringer_blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_mvp_painbringer_gold {
            get {
                object obj = ResourceManager.GetObject("storm_ui_mvp_painbringer_gold", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_mvp_painbringer_red {
            get {
                object obj = ResourceManager.GetObject("storm_ui_mvp_painbringer_red", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_mvp_pointguard_blue {
            get {
                object obj = ResourceManager.GetObject("storm_ui_mvp_pointguard_blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_mvp_pointguard_gold {
            get {
                object obj = ResourceManager.GetObject("storm_ui_mvp_pointguard_gold", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_mvp_pointguard_red {
            get {
                object obj = ResourceManager.GetObject("storm_ui_mvp_pointguard_red", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_mvp_protector_blue {
            get {
                object obj = ResourceManager.GetObject("storm_ui_mvp_protector_blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_mvp_protector_gold {
            get {
                object obj = ResourceManager.GetObject("storm_ui_mvp_protector_gold", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_mvp_protector_red {
            get {
                object obj = ResourceManager.GetObject("storm_ui_mvp_protector_red", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_mvp_pusher_blue {
            get {
                object obj = ResourceManager.GetObject("storm_ui_mvp_pusher_blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_mvp_pusher_gold {
            get {
                object obj = ResourceManager.GetObject("storm_ui_mvp_pusher_gold", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_mvp_pusher_red {
            get {
                object obj = ResourceManager.GetObject("storm_ui_mvp_pusher_red", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_mvp_scrapper_blue {
            get {
                object obj = ResourceManager.GetObject("storm_ui_mvp_scrapper_blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_mvp_scrapper_gold {
            get {
                object obj = ResourceManager.GetObject("storm_ui_mvp_scrapper_gold", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_mvp_scrapper_red {
            get {
                object obj = ResourceManager.GetObject("storm_ui_mvp_scrapper_red", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_mvp_shriner_blue {
            get {
                object obj = ResourceManager.GetObject("storm_ui_mvp_shriner_blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_mvp_shriner_gold {
            get {
                object obj = ResourceManager.GetObject("storm_ui_mvp_shriner_gold", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_mvp_shriner_red {
            get {
                object obj = ResourceManager.GetObject("storm_ui_mvp_shriner_red", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_mvp_siegemaster_blue {
            get {
                object obj = ResourceManager.GetObject("storm_ui_mvp_siegemaster_blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_mvp_siegemaster_gold {
            get {
                object obj = ResourceManager.GetObject("storm_ui_mvp_siegemaster_gold", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_mvp_siegemaster_red {
            get {
                object obj = ResourceManager.GetObject("storm_ui_mvp_siegemaster_red", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_mvp_silencer_blue {
            get {
                object obj = ResourceManager.GetObject("storm_ui_mvp_silencer_blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_mvp_silencer_gold {
            get {
                object obj = ResourceManager.GetObject("storm_ui_mvp_silencer_gold", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_mvp_silencer_red {
            get {
                object obj = ResourceManager.GetObject("storm_ui_mvp_silencer_red", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_mvp_skullcollector_blue {
            get {
                object obj = ResourceManager.GetObject("storm_ui_mvp_skullcollector_blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_mvp_skullcollector_gold {
            get {
                object obj = ResourceManager.GetObject("storm_ui_mvp_skullcollector_gold", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_mvp_skullcollector_red {
            get {
                object obj = ResourceManager.GetObject("storm_ui_mvp_skullcollector_red", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_mvp_solesurvivor_blue {
            get {
                object obj = ResourceManager.GetObject("storm_ui_mvp_solesurvivor_blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_mvp_solesurvivor_gold {
            get {
                object obj = ResourceManager.GetObject("storm_ui_mvp_solesurvivor_gold", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_mvp_solesurvivor_red {
            get {
                object obj = ResourceManager.GetObject("storm_ui_mvp_solesurvivor_red", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_mvp_stunner_blue {
            get {
                object obj = ResourceManager.GetObject("storm_ui_mvp_stunner_blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_mvp_stunner_gold {
            get {
                object obj = ResourceManager.GetObject("storm_ui_mvp_stunner_gold", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_mvp_stunner_red {
            get {
                object obj = ResourceManager.GetObject("storm_ui_mvp_stunner_red", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_mvp_teamplayer_blue {
            get {
                object obj = ResourceManager.GetObject("storm_ui_mvp_teamplayer_blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_mvp_teamplayer_gold {
            get {
                object obj = ResourceManager.GetObject("storm_ui_mvp_teamplayer_gold", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_mvp_teamplayer_red {
            get {
                object obj = ResourceManager.GetObject("storm_ui_mvp_teamplayer_red", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_mvp_templemaster_blue {
            get {
                object obj = ResourceManager.GetObject("storm_ui_mvp_templemaster_blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_mvp_templemaster_gold {
            get {
                object obj = ResourceManager.GetObject("storm_ui_mvp_templemaster_gold", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_mvp_templemaster_red {
            get {
                object obj = ResourceManager.GetObject("storm_ui_mvp_templemaster_red", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_mvp_trapper_blue {
            get {
                object obj = ResourceManager.GetObject("storm_ui_mvp_trapper_blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_mvp_trapper_gold {
            get {
                object obj = ResourceManager.GetObject("storm_ui_mvp_trapper_gold", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_mvp_trapper_red {
            get {
                object obj = ResourceManager.GetObject("storm_ui_mvp_trapper_red", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_mvp_zergcrusher_blue {
            get {
                object obj = ResourceManager.GetObject("storm_ui_mvp_zergcrusher_blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_mvp_zergcrusher_gold {
            get {
                object obj = ResourceManager.GetObject("storm_ui_mvp_zergcrusher_gold", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_mvp_zergcrusher_red {
            get {
                object obj = ResourceManager.GetObject("storm_ui_mvp_zergcrusher_red", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_scorescreen_mvp_avenger_blue {
            get {
                object obj = ResourceManager.GetObject("storm_ui_scorescreen_mvp_avenger_blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_scorescreen_mvp_avenger_red {
            get {
                object obj = ResourceManager.GetObject("storm_ui_scorescreen_mvp_avenger_red", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_scorescreen_mvp_bulwark_blue {
            get {
                object obj = ResourceManager.GetObject("storm_ui_scorescreen_mvp_bulwark_blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_scorescreen_mvp_bulwark_red {
            get {
                object obj = ResourceManager.GetObject("storm_ui_scorescreen_mvp_bulwark_red", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_scorescreen_mvp_cannoneer_blue {
            get {
                object obj = ResourceManager.GetObject("storm_ui_scorescreen_mvp_cannoneer_blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_scorescreen_mvp_cannoneer_red {
            get {
                object obj = ResourceManager.GetObject("storm_ui_scorescreen_mvp_cannoneer_red", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_scorescreen_mvp_clutchhealer_blue {
            get {
                object obj = ResourceManager.GetObject("storm_ui_scorescreen_mvp_clutchhealer_blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_scorescreen_mvp_clutchhealer_red {
            get {
                object obj = ResourceManager.GetObject("storm_ui_scorescreen_mvp_clutchhealer_red", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_scorescreen_mvp_combatmedic_blue {
            get {
                object obj = ResourceManager.GetObject("storm_ui_scorescreen_mvp_combatmedic_blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_scorescreen_mvp_combatmedic_red {
            get {
                object obj = ResourceManager.GetObject("storm_ui_scorescreen_mvp_combatmedic_red", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_scorescreen_mvp_dabomb_blue {
            get {
                object obj = ResourceManager.GetObject("storm_ui_scorescreen_mvp_dabomb_blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_scorescreen_mvp_dabomb_red {
            get {
                object obj = ResourceManager.GetObject("storm_ui_scorescreen_mvp_dabomb_red", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_scorescreen_mvp_daredevil_blue {
            get {
                object obj = ResourceManager.GetObject("storm_ui_scorescreen_mvp_daredevil_blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_scorescreen_mvp_daredevil_red {
            get {
                object obj = ResourceManager.GetObject("storm_ui_scorescreen_mvp_daredevil_red", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_scorescreen_mvp_escapeartist_blue {
            get {
                object obj = ResourceManager.GetObject("storm_ui_scorescreen_mvp_escapeartist_blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_scorescreen_mvp_escapeartist_red {
            get {
                object obj = ResourceManager.GetObject("storm_ui_scorescreen_mvp_escapeartist_red", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_scorescreen_mvp_experienced_blue {
            get {
                object obj = ResourceManager.GetObject("storm_ui_scorescreen_mvp_experienced_blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_scorescreen_mvp_experienced_red {
            get {
                object obj = ResourceManager.GetObject("storm_ui_scorescreen_mvp_experienced_red", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_scorescreen_mvp_finisher_blue {
            get {
                object obj = ResourceManager.GetObject("storm_ui_scorescreen_mvp_finisher_blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_scorescreen_mvp_finisher_red {
            get {
                object obj = ResourceManager.GetObject("storm_ui_scorescreen_mvp_finisher_red", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_scorescreen_mvp_gardenterror_blue {
            get {
                object obj = ResourceManager.GetObject("storm_ui_scorescreen_mvp_gardenterror_blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_scorescreen_mvp_gardenterror_red {
            get {
                object obj = ResourceManager.GetObject("storm_ui_scorescreen_mvp_gardenterror_red", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_scorescreen_mvp_guardian_blue {
            get {
                object obj = ResourceManager.GetObject("storm_ui_scorescreen_mvp_guardian_blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_scorescreen_mvp_guardian_red {
            get {
                object obj = ResourceManager.GetObject("storm_ui_scorescreen_mvp_guardian_red", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_scorescreen_mvp_guardianslayer_blue {
            get {
                object obj = ResourceManager.GetObject("storm_ui_scorescreen_mvp_guardianslayer_blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_scorescreen_mvp_guardianslayer_red {
            get {
                object obj = ResourceManager.GetObject("storm_ui_scorescreen_mvp_guardianslayer_red", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_scorescreen_mvp_hattrick_blue {
            get {
                object obj = ResourceManager.GetObject("storm_ui_scorescreen_mvp_hattrick_blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_scorescreen_mvp_hattrick_red {
            get {
                object obj = ResourceManager.GetObject("storm_ui_scorescreen_mvp_hattrick_red", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_scorescreen_mvp_headhunter_blue {
            get {
                object obj = ResourceManager.GetObject("storm_ui_scorescreen_mvp_headhunter_blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_scorescreen_mvp_headhunter_red {
            get {
                object obj = ResourceManager.GetObject("storm_ui_scorescreen_mvp_headhunter_red", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_scorescreen_mvp_immortalslayer_blue {
            get {
                object obj = ResourceManager.GetObject("storm_ui_scorescreen_mvp_immortalslayer_blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_scorescreen_mvp_immortalslayer_red {
            get {
                object obj = ResourceManager.GetObject("storm_ui_scorescreen_mvp_immortalslayer_red", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_scorescreen_mvp_jeweler_blue {
            get {
                object obj = ResourceManager.GetObject("storm_ui_scorescreen_mvp_jeweler_blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_scorescreen_mvp_jeweler_red {
            get {
                object obj = ResourceManager.GetObject("storm_ui_scorescreen_mvp_jeweler_red", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_scorescreen_mvp_loyaldefender_wcav_blue {
            get {
                object obj = ResourceManager.GetObject("storm_ui_scorescreen_mvp_loyaldefender_wcav_blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_scorescreen_mvp_loyaldefender_wcav_red {
            get {
                object obj = ResourceManager.GetObject("storm_ui_scorescreen_mvp_loyaldefender_wcav_red", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_scorescreen_mvp_mainhealer_blue {
            get {
                object obj = ResourceManager.GetObject("storm_ui_scorescreen_mvp_mainhealer_blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_scorescreen_mvp_mainhealer_red {
            get {
                object obj = ResourceManager.GetObject("storm_ui_scorescreen_mvp_mainhealer_red", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_scorescreen_mvp_masterofthecurse_blue {
            get {
                object obj = ResourceManager.GetObject("storm_ui_scorescreen_mvp_masterofthecurse_blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_scorescreen_mvp_masterofthecurse_red {
            get {
                object obj = ResourceManager.GetObject("storm_ui_scorescreen_mvp_masterofthecurse_red", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_scorescreen_mvp_moneybags_blue {
            get {
                object obj = ResourceManager.GetObject("storm_ui_scorescreen_mvp_moneybags_blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_scorescreen_mvp_moneybags_red {
            get {
                object obj = ResourceManager.GetObject("storm_ui_scorescreen_mvp_moneybags_red", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_scorescreen_mvp_mvp_blue {
            get {
                object obj = ResourceManager.GetObject("storm_ui_scorescreen_mvp_mvp_blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_scorescreen_mvp_mvp_red {
            get {
                object obj = ResourceManager.GetObject("storm_ui_scorescreen_mvp_mvp_red", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_scorescreen_mvp_painbringer_blue {
            get {
                object obj = ResourceManager.GetObject("storm_ui_scorescreen_mvp_painbringer_blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_scorescreen_mvp_painbringer_red {
            get {
                object obj = ResourceManager.GetObject("storm_ui_scorescreen_mvp_painbringer_red", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_scorescreen_mvp_pointguard_blue {
            get {
                object obj = ResourceManager.GetObject("storm_ui_scorescreen_mvp_pointguard_blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_scorescreen_mvp_pointguard_red {
            get {
                object obj = ResourceManager.GetObject("storm_ui_scorescreen_mvp_pointguard_red", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_scorescreen_mvp_protector_blue {
            get {
                object obj = ResourceManager.GetObject("storm_ui_scorescreen_mvp_protector_blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_scorescreen_mvp_protector_red {
            get {
                object obj = ResourceManager.GetObject("storm_ui_scorescreen_mvp_protector_red", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_scorescreen_mvp_pusher_blue {
            get {
                object obj = ResourceManager.GetObject("storm_ui_scorescreen_mvp_pusher_blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_scorescreen_mvp_pusher_red {
            get {
                object obj = ResourceManager.GetObject("storm_ui_scorescreen_mvp_pusher_red", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_scorescreen_mvp_scrapper_blue {
            get {
                object obj = ResourceManager.GetObject("storm_ui_scorescreen_mvp_scrapper_blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_scorescreen_mvp_scrapper_red {
            get {
                object obj = ResourceManager.GetObject("storm_ui_scorescreen_mvp_scrapper_red", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_scorescreen_mvp_shriner_blue {
            get {
                object obj = ResourceManager.GetObject("storm_ui_scorescreen_mvp_shriner_blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_scorescreen_mvp_shriner_red {
            get {
                object obj = ResourceManager.GetObject("storm_ui_scorescreen_mvp_shriner_red", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_scorescreen_mvp_siegemaster_blue {
            get {
                object obj = ResourceManager.GetObject("storm_ui_scorescreen_mvp_siegemaster_blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_scorescreen_mvp_siegemaster_red {
            get {
                object obj = ResourceManager.GetObject("storm_ui_scorescreen_mvp_siegemaster_red", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_scorescreen_mvp_silencer_blue {
            get {
                object obj = ResourceManager.GetObject("storm_ui_scorescreen_mvp_silencer_blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_scorescreen_mvp_silencer_red {
            get {
                object obj = ResourceManager.GetObject("storm_ui_scorescreen_mvp_silencer_red", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_scorescreen_mvp_skull_blue {
            get {
                object obj = ResourceManager.GetObject("storm_ui_scorescreen_mvp_skull_blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_scorescreen_mvp_skull_red {
            get {
                object obj = ResourceManager.GetObject("storm_ui_scorescreen_mvp_skull_red", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_scorescreen_mvp_skullcollector_blue {
            get {
                object obj = ResourceManager.GetObject("storm_ui_scorescreen_mvp_skullcollector_blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_scorescreen_mvp_skullcollector_red {
            get {
                object obj = ResourceManager.GetObject("storm_ui_scorescreen_mvp_skullcollector_red", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_scorescreen_mvp_solesurvivor_blue {
            get {
                object obj = ResourceManager.GetObject("storm_ui_scorescreen_mvp_solesurvivor_blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_scorescreen_mvp_solesurvivor_red {
            get {
                object obj = ResourceManager.GetObject("storm_ui_scorescreen_mvp_solesurvivor_red", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_scorescreen_mvp_stunner_blue {
            get {
                object obj = ResourceManager.GetObject("storm_ui_scorescreen_mvp_stunner_blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_scorescreen_mvp_stunner_red {
            get {
                object obj = ResourceManager.GetObject("storm_ui_scorescreen_mvp_stunner_red", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_scorescreen_mvp_teamplayer_blue {
            get {
                object obj = ResourceManager.GetObject("storm_ui_scorescreen_mvp_teamplayer_blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_scorescreen_mvp_teamplayer_red {
            get {
                object obj = ResourceManager.GetObject("storm_ui_scorescreen_mvp_teamplayer_red", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_scorescreen_mvp_templemaster_blue {
            get {
                object obj = ResourceManager.GetObject("storm_ui_scorescreen_mvp_templemaster_blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_scorescreen_mvp_templemaster_red {
            get {
                object obj = ResourceManager.GetObject("storm_ui_scorescreen_mvp_templemaster_red", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_scorescreen_mvp_trapper_blue {
            get {
                object obj = ResourceManager.GetObject("storm_ui_scorescreen_mvp_trapper_blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_scorescreen_mvp_trapper_red {
            get {
                object obj = ResourceManager.GetObject("storm_ui_scorescreen_mvp_trapper_red", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_scorescreen_mvp_zergcrusher_blue {
            get {
                object obj = ResourceManager.GetObject("storm_ui_scorescreen_mvp_zergcrusher_blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_ui_scorescreen_mvp_zergcrusher_red {
            get {
                object obj = ResourceManager.GetObject("storm_ui_scorescreen_mvp_zergcrusher_red", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
